 ENT.Type			 = "anim"  
 ENT.Base 			= "base_gmodentity"     
 ENT.PrintName			= "5.56mm Ball"  
 ENT.Author			= "Generic Default"  
 ENT.Contact			= "AIDS"  
 ENT.Purpose			= "Killing"  
 ENT.Instructions			= "SHOOT"  
 ENT.Spawnable			= false
ENT.AdminSpawnable		= false
