list.Set( "NPCWeapons", "gdcw_m4a1iron", "GDCW M4A1 Iron" )
list.Set( "NPCWeapons", "gdcw_m4a1acog", "GDCW M4A1 ACOG" )
list.Set( "NPCWeapons", "gdcw_m4a1holo", "GDCW M4A1 Holo" )
list.Set( "NPCWeapons", "gdcw_ak47iron", "GDCW AK47" )
list.Set( "NPCWeapons", "gdcw_hk416iron", "GDCW HK416" )
list.Set( "NPCWeapons", "gdcw_p90iron", "GDCW P90" )
list.Set( "NPCWeapons", "gdcw_g36cacog", "GDCW G36C" )
list.Set( "NPCWeapons", "gdcw_m16holo", "GDCW M16 Holo" )
list.Set( "NPCWeapons", "gdcw_m16acog", "GDCW M16 ACOG" )
list.Set( "NPCWeapons", "gdcw_m16iron", "GDCW M16 Iron" )
list.Set( "NPCWeapons", "gdcw_m16rdot", "GDCW M16 Red Dot" )
list.Set( "NPCWeapons", "gdcw_falscope", "GDCW FAL" )
list.Set( "NPCWeapons", "gdcw_p228", "GDCW P228" )
list.Set( "NPCWeapons", "gdcw_m9", "GDCW M9" )
list.Set( "NPCWeapons", "gdcw_fiveseven", "GDCW Fiveseven" )
list.Set( "NPCWeapons", "gdcw_glock18", "GDCW Glock 18" )
list.Set( "NPCWeapons", "gdcw_deagle", "GDCW Deagle" )
list.Set( "NPCWeapons", "gdcw_m1911", "GDCW M1911" )
list.Set( "NPCWeapons", "gdcw_revolver", "GDCW Revolver" )
list.Set( "NPCWeapons", "gdcw_miniuzi", "GDCW Uzi" )
list.Set( "NPCWeapons", "gdcw_m240", "GDCW M240" )
list.Set( "NPCWeapons", "gdcw_hk21", "GDCW HK21" )
list.Set( "NPCWeapons", "gdcw_sg552", "GDCW SG552 Iron" )
list.Set( "NPCWeapons", "gdcw_awpunscoped", "GDCW Unscoped AWP" )
list.Set( "NPCWeapons", "gdcw_hl2_pistol", "GDCW HL2 Pistol" )
list.Set( "NPCWeapons", "gdcw_hl2_smg1", "GDCW HL2 SMG1" )
list.Set( "NPCWeapons", "gdcw_hl2_revolver", "GDCW HL2 Revolver" )