list.Set( "NPCWeapons", "gdcw_masada", "GDCW Masada" )
list.Set( "NPCWeapons", "gdcw_m4a1iron", "GDCW M4A1 Iron" )
list.Set( "NPCWeapons", "gdcw_m4a1acog", "GDCW M4A1 ACOG" )
list.Set( "NPCWeapons", "gdcw_m4a1holo", "GDCW M4A1 Holo" )
list.Set( "NPCWeapons", "gdcw_ak47iron", "GDCW AK47" )
list.Set( "NPCWeapons", "gdcw_hk416iron", "GDCW HK416" )
list.Set( "NPCWeapons", "gdcw_g36cacog", "GDCW G36C" )
list.Set( "NPCWeapons", "gdcw_m16holo", "GDCW M16 Holo" )
list.Set( "NPCWeapons", "gdcw_m16acog", "GDCW M16 ACOG" )
list.Set( "NPCWeapons", "gdcw_m16iron", "GDCW M16 Iron" )
list.Set( "NPCWeapons", "gdcw_m16rdot", "GDCW M16 Red Dot" )
list.Set( "NPCWeapons", "gdcw_falscope", "GDCW FAL" )
list.Set( "NPCWeapons", "gdcw_sg552", "GDCW SG552 Iron" )
