list.Set( "NPCWeapons", "weapon_shotgun", "Shotgun" )
list.Set( "NPCWeapons", "weapon_Crossbow", "Crossbow" )
list.Set( "NPCWeapons", "weapon_pistol", "Pistol" )
list.Set( "NPCWeapons", "weapon_smg1", "SMG1" )
list.Set( "NPCWeapons", "weapon_ar2", "AR2" )
list.Set( "NPCWeapons", "weapon_crowbar", "Crowbar" )
list.Set( "NPCWeapons", "weapon_rpg", "RPG" )
list.Set( "NPCWeapons", "weapon_357", "357" )
list.Set( "NPCWeapons", "weapon_annabelle", "Annabelle" )
list.Set( "NPCWeapons", "weapon_stunstick", "Stunstick" )
list.Set( "NPCWeapons", "gdcw_m4a1iron", "GDCW M4A1 Iron" )
list.Set( "NPCWeapons", "gdcw_m4a1acog", "GDCW M4A1 ACOG" )
list.Set( "NPCWeapons", "gdcw_m4a1holo", "GDCW M4A1 Holo" )
list.Set( "NPCWeapons", "gdcw_ak47iron", "GDCW AK47" )
list.Set( "NPCWeapons", "gdcw_hk416iron", "GDCW HK416" )
list.Set( "NPCWeapons", "gdcw_p90iron", "GDCW P90" )
list.Set( "NPCWeapons", "gdcw_g36cacog", "GDCW G36C" )
list.Set( "NPCWeapons", "gdcw_m16holo", "GDCW M16 Holo" )
list.Set( "NPCWeapons", "gdcw_m16acog", "GDCW M16 ACOG" )
list.Set( "NPCWeapons", "gdcw_m16iron", "GDCW M16 Iron" )
list.Set( "NPCWeapons", "gdcw_m16rdot", "GDCW M16 Red Dot" )
list.Set( "NPCWeapons", "gdcw_fal", "GDCW FAL" )