ENT.Type			 = "anim"  
ENT.Base 			= "base_gmodentity"     
ENT.PrintName			= "Buckshot"  
ENT.Author			= "Generic Default"  
ENT.Contact			= "AIDS"  
ENT.Purpose			= "Killing"  
ENT.Instructions		= "SHOOT"  
ENT.Spawnable			= false
ENT.AdminSpawnable		= false
