// Variables that are used on both client and server
SWEP.Category				= "Generic Default's Weapons"
SWEP.Author				= "Generic Default"
SWEP.Contact				= "AIDS!"
SWEP.Purpose				= "Jihadding"
SWEP.Instructions			= "Round: 7.62 \nVelocity: ~715 m/s \nSights: Iron, Red Dot, Holo, ACOG \nCapacity: 30 rounds \nRate of Fire: 600 rounds per minute"
SWEP.MuzzleAttachment			= "1" 	-- Should be "1" for CSS models or "muzzle" for hl2 models
SWEP.ShellEjectAttachment		= "2" 	-- Should be "2" for CSS models or "1" for hl2 models
SWEP.DrawCrosshair			= false	

SWEP.ViewModelFOV			= 55
SWEP.ViewModelFlip			= true
SWEP.ViewModel				= "models/weapons/v_GDCAKDOT.mdl"
SWEP.WorldModel				= "models/weapons/w_GDCAK47.mdl"
SWEP.Base 				= "gdcw_base_assault_emenu"
SWEP.Spawnable				= true
SWEP.AdminSpawnable			= true

SWEP.Primary.Sound			= Sound("AK47F.single")
SWEP.Primary.Ball 			= ("gdcwa_7.62x39_ball")		// FMJ round
SWEP.Primary.Hollow 			= ("gdcwa_7.62x39_hollow")		// Hollow point round
SWEP.Primary.AP 			= ("gdcwa_7.62x39_ap")			// Armor Piercing round
SWEP.Primary.HEI 			= ("gdcwa_7.62x39_hei")			// High Explosive Incendiary round
SWEP.Primary.RPM			= 600					// This is in Rounds Per Minute
SWEP.Primary.ClipSize			= 30					// Size of a clip
SWEP.Primary.DefaultClip		= 31					// Default number of bullets in a clip
SWEP.Primary.ConeSpray			= 2.0					// Hip fire accuracy
SWEP.Primary.ConeIncrement		= 2.0					// Rate of innacuracy
SWEP.Primary.ConeMax			= 5.0					// Maximum Innacuracy
SWEP.Primary.ConeDecrement		= 0.1					// Rate of accuracy
SWEP.Primary.KickUp			= 0.5					// Maximum up recoil (rise)
SWEP.Primary.KickDown			= 0.4					// Maximum down recoil (skeet)
SWEP.Primary.KickHorizontal		= 0.4					// Maximum up recoil (stock)
SWEP.Primary.Automatic			= true					// Automatic/Semi Auto
SWEP.Primary.Ammo			= "ar2"

SWEP.Secondary.ClipSize			= 1					// Size of a clip
SWEP.Secondary.DefaultClip		= 1					// Default number of bullets in a clip
SWEP.Secondary.Automatic		= false					// Automatic/Semi Auto
SWEP.Secondary.Ammo			= ""
SWEP.Secondary.IronFOV			= 40					// How much you 'zoom' in. Less is more! 
SWEP.Secondary.ScopeZoom		= 4					// How much the scope magnifies
SWEP.Secondary.UseACOG			= true	
SWEP.Secondary.UseMilDot		= false		
SWEP.Secondary.UseSVD			= false	
SWEP.Secondary.UseParabolic		= false	
SWEP.Secondary.UseElcan			= false
SWEP.Secondary.UseGreenDuplex		= false	
SWEP.Secondary.UseRangefinder		= false	
SWEP.ScopeScale 			= 0.5					// This is the size of the scope overlay
SWEP.ReticleScale 			= 0.6					// This is the size of the scope crosshairs
SWEP.CrossScale 			= 0.07
SWEP.SightMode				= 1

SWEP.data 				= {}					-- The starting firemode
SWEP.data.ironsights			= 1
SWEP.Silenceable			= false
SWEP.Silenced				= false
SWEP.BurstCapable			= false

SWEP.HasIronModel			= 1
SWEP.IronVModel				= "models/weapons/v_GDCAKIRO.mdl"
SWEP.IronWModel				= "models/weapons/w_GDCAK47.mdl"
SWEP.HasRDotModel			= 1
SWEP.RDotVModel				= "models/weapons/v_GDCAKDOT.mdl"
SWEP.RDotWModel				= "models/weapons/w_GDCAK47.mdl"
SWEP.HasHoloModel			= 1
SWEP.HoloVModel				= "models/weapons/v_GDCAKHOL.mdl"
SWEP.HoloWModel				= "models/weapons/w_GDCAK47.mdl"
SWEP.HasACOGModel			= 1
SWEP.ACOGVModel				= "models/weapons/v_GDCAKACO.mdl"
SWEP.ACOGWModel				= "models/weapons/w_GDCAK47.mdl"

SWEP.IronSightsPos = Vector (4.4472, -5.4266, 1.6892)
SWEP.IronSightsAng =Vector (0, 0, 0)
SWEP.SightsPos = Vector (4.4472, -5.4266, 1.6892)
SWEP.SightsAng = Vector (0, 0, 0)
SWEP.RunSightsPos = Vector (-2.3095, -3.0514, 2.3965)
SWEP.RunSightsAng = Vector (-19.8471, -33.9181, 10)
SWEP.WallSightsPos = Vector (1.0247, -15.0908, -3.7047)
SWEP.WallSightsAng = Vector (57.4589, 3.9491, 0)

SWEP.ISPos = Vector (4.5347, -4.2492, 1.843)
SWEP.ISAng = Vector (0.6247, -0.0475, 0)
SWEP.RSPos = Vector (4.4472, -5.4266, 1.6892)
SWEP.RSAng = Vector (0, 0, 0)
SWEP.HSPos = Vector (4.4552, -1.3711, 1.2063)
SWEP.HSAng = Vector (0, 0, 0)
SWEP.ASPos = Vector (4.4601, -7.3797, 1.1813)
SWEP.ASAng = Vector (0, 0, 0)
