ENT.Type 			= "anim"  
ENT.Base 			= "base_anim"     
ENT.PrintName			= "5.56mm AP-T"  
ENT.Author			= "Generic Default"  
ENT.Contact			= "AIDS"  
ENT.Purpose			= "Shoot Stuff"  
ENT.Instructions		= "Bustin caps"  
ENT.Spawnable			= false
ENT.AdminSpawnable		= false