/*------------------------------------------------------------------------------------------------------------------
								NORMAL DOWNLOADS
------------------------------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------
 Materials
---------------------------------------------------------*/

resource.AddFile( "materials/scope/gdcw_noise.vtf" );
resource.AddFile( "materials/scope/gdcw_acogcross.vmt" );
resource.AddFile( "materials/scope/gdcw_acogcross.vtf" );
resource.AddFile( "materials/scope/gdcw_acogchevron.vmt" );
resource.AddFile( "materials/scope/gdcw_acogchevron.vtf" );
resource.AddFile( "materials/scope/gdcw_elcansight.vmt" );
resource.AddFile( "materials/scope/gdcw_elcansight.vtf" );
resource.AddFile( "materials/scope/gdcw_elcanreticle.vmt" );
resource.AddFile( "materials/scope/gdcw_elcanreticle.vtf" );
resource.AddFile( "materials/scope/gdcw_closedsight.vmt" );
resource.AddFile( "materials/scope/gdcw_closedsight.vtf" );
resource.AddFile( "materials/scope/gdcw_parabolicsight.vtf" );
resource.AddFile( "materials/scope/gdcw_parabolicsight.vmf" );
resource.AddFile( "materials/scope/gdcw_scopesight.vtf" );
resource.AddFile( "materials/scope/gdcw_scopesight.vmf" );
resource.AddFile( "materials/scope/gdcw_svdsight.vtf" );
resource.AddFile( "materials/scope/gdcw_svdsight.vmf" );

resource.AddFile( "materials/VGUI/entities/gdcw_ak47acog.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47dot.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47holo.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47iron.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1iron.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1holo.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1acog.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416iron.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416acog.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416holo.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416dot.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90rdot.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90holo.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90acog.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90iron.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m82.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_as50.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_awp.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_fal.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m24.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m76.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_g36.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16iron.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16rdot.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16holo.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16acog.vtf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47acog.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47dot.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47holo.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_ak47iron.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1iron.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1holo.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m4a1acog.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416iron.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416acog.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416holo.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_hk416dot.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90rdot.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90holo.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90acog.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_p90iron.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m82.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_as50.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_awp.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_fal.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m24.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m76.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_g36.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16iron.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16rdot.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16holo.vmf" );
resource.AddFile( "materials/VGUI/entities/gdcw_m16acog.vmf" );


resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/body.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/body_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech553.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech557.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech_lens.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech_magnifier.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/foregrip.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/foregrip_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/frame1.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/glass.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/linse.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/mag.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/mag_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/ris.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/ris_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/sight.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/sight_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/body.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech553.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech557.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech_lens.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/eotech_magnifier.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/foregrip.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/frame1.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/glass.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/linse.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/mag.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/ris.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Colt M4 R.I.S/sight.vmt" );

resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/acognormal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/barrel.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/barrel_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/carry.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/carry_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotec.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotec_selfillum.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotech.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotech_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/fore.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/forenormal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gemtech.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gemtech_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/grip.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gucci.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gucci_bump.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lens.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lens_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lower_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lower.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/mag_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/mag.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magnifier.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magnifier_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magpul.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magpul_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/newacog.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/Pmag.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/Pmag_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/pmagpul.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/pmagpul_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/upper.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/upper_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/acoguv.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/barrel.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/carry.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotec.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/eotech.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/fore.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gemtech.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/grip.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/gucci.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lens.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/lower.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/mag.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magnifier.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/magpul.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/Pmag.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/pmagpul.vmt" );
resource.AddFile( "materials/models/weapons/v_models/Twinke.M4/upper.vmt" );

resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/acog.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/acog_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/eotech553.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/eotech_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/frame1.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/glass.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/linse.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/magazine.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/magazine_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/newscope.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/receiver.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/receiver_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/trit.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/upper.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/upper_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/47_mag.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/47_rec.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/acog.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/eotech553.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/frame1.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/glass.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/linse.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/newscope.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/receiver.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/trit.vmf" );
resource.AddFile( "materials/models/weapons/v_models/Thanez_AK/upper.vmf" );

resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/acoguv.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/acoguv_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/body.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/body_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/bullet.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/bullet_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/clip.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/clip_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/docter.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/docter_ref.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/eot.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/eot_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/lens.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/linse.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/misc.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/misc_bump.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/rail_reciever.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/rail_reciever_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/silencer.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/silencer_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/spring.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/spring_normal.vtf" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/acoguv.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/body.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/bullet.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/clip.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/docter.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/eot.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/lens.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/misc.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/rail_reciever.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/reciever.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/silencer.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/spring.vmt" );
resource.AddFile( "materials/models/weapons/v_models/SF.Thanez_P90/red_cross.vmt" );




resource.AddFile( "materials/models/weapons/w_models/Colt M4 R.I.S/body.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Colt M4 R.I.S/mag.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Colt M4 R.I.S/ris.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Colt M4 R.I.S/sight.vmt" );

resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/body.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/bullet.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/clip.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/rail_reciever.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/reciever.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/silencer.vmt" );
resource.AddFile( "materials/models/weapons/w_models/SF.Thanez_P90/spring.vmt" );

resource.AddFile( "materials/models/weapons/w_models/Thanez_AK/magazine.vmf" );
resource.AddFile( "materials/models/weapons/w_models/Thanez_AK/receiver.vmf" );
resource.AddFile( "materials/models/weapons/w_models/Thanez_AK/upper.vmf" );

resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/barrel.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/carry.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/eotec.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/eotech.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/fore.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/gemtech.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/grip.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/gucci.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/lens.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/lower.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/mag.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/magnifier.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/magpul.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/newacog.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/Pmag.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/upper.vtf" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/acoguv.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/barrel.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/carry.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/eotec.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/eotech.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/fore.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/gemtech.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/grip.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/gucci.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/lens.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/lower.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/mag.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/magnifier.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/magpul.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/Pmag.vmt" );
resource.AddFile( "materials/models/weapons/w_models/Twinke.M4/upper.vmt" );